### ISSUE TITLE
Use JSValue whenever is possible

### ISSUE THREAD

**Issue by jleni** [Zondax/filecoin-rs#119]
Try to use JSValue and autodetect input type. That way we can handle JSON as dictionaries or strings and minimize the use of stringify. Similarly, hexstrings vs Buffer/UInt8Array

**Comment by jleni** [comment]
In some of our methods, we are already using JSValue instead of specific types. It would be nice to review the API and move arguments to JSValue when possible. This means that the implementation can check for different types (dict vs string vs buffer/uint8array) and treat them correctly. What way the same API will work for both buffers and hexstrings.

**Comment by rllola** [comment]
It would impact the following functions :
- `key_derive_from_seed`-> the seed input would be JsValue;
- `key_recover` -> the private key string input would be a JsValue;
- `transaction_serialize` & `transaction_serialize_raw` -> the message would be a JsValue and not a string anymore;
- `transaction_parse` -> the cbor transaction input would change for JsValue type;
- `transaction_sign` -> the tx is already a JsValue but not the private key;
- `verify_signature` -> the signature and the message would be converted to JsValue;

Orther arguments like `mnemonic`, `password` or `path` can be kept as String.
