### ISSUE TITLE
Re-enable `send_sign` and `send_signed_tx` test

### ISSUE THREAD

**Issue by rllola** [Zondax/filecoin-rs#120]
Don't skip `send_sign` and `send_signed_tx` tests when the lotus node has been upgraded to testnet/3 standards.

See https://github.com/Zondax/filecoin-rs/pull/113#issuecomment-613410212

**Comment by jleni** [comment]
Related to #124

**Comment by jleni** [comment]
@rllola this should be relatively easy now
