### ISSUE TITLE
testnet3 support tracking issue

### ISSUE THREAD

**Issue by Schwartz10** [Zondax/filecoin-rs#124]
Just filing this issue to track testnet3 support progress in the wasm library. The current (published) npm version `0.3.1` is not working with testnet/3.

**Comment by jleni** [comment]
A breaking change related to testnet/3 has been recently integrated: https://github.com/filecoin-project/lotus/pull/1619

We are now unblocked and will upgrade to testnet/3 very soon

**Comment by jleni** [comment]
related issue https://github.com/Zondax/ledger-filecoin/issues/40
