### ISSUE TITLE
api.rs file error 

### ISSUE THREAD

**Issue by ldjdsc** [Zondax/filecoin-rs#138]
error[E0423]: expected function, tuple struct or tuple variant, found type alias `TokenAmount`
   --> signer/src/api.rs:184:20
    |
184 |             .value(TokenAmount(value))
    |                    ^^^^^^^^^^^
    |
    = note: can't use a type alias as a constructor

error[E0599]: no function or associated item named `new` found for type `u64` in the current scope
   --> signer/src/api.rs:185:36
    |
185 |             .method_num(MethodNum::new(message_api.method))
    |                                    ^^^ function or associated item not found in `u64`

error[E0308]: mismatched types
   --> signer/src/api.rs:187:24
    |
187 |             .gas_limit(gas_limit)
    |                        ^^^^^^^^^ expected `u64`, found struct `num_bigint::biguint::BigUint`

error[E0609]: no field `0` on type `&num_bigint::biguint::BigUint`
   --> signer/src/api.rs:202:45
    |
202 |             value: unsigned_message.value().0.to_string(),
    |                                             ^ unknown field

error: aborting due to 4 previous errors

**Comment by jleni** [comment]
Hi @ldjdsc there have been changes in the specs between testnet/2 and testnet/3. 

Most important breaking changes:
- gasLimit changed from bigint to u64.  
- a tx version field has been added (filecoin-project/lotus#1619)

Now that all our dependencies and testnet/3 infrastructure is ready, we are upgrading everything to testnet/3 and merging dev to master. (https://github.com/Zondax/filecoin-rs/issues/124)

At that point, things will get much more stable. We expect to merge this in the next couple of days.
