### ISSUE TITLE
Deny expect and unwrap on CI

### ISSUE THREAD

**Issue by c410-f3r** [Zondax/filecoin-rs#146]
Some things need to fixed before enforcing the `clippy::option_unwrap_used`, `clippy::option_expect_used`, `clippy::result_unwrap_used` and `clippy::result_expect_used` lints on CI:

- [ ] **FFI**: Some functions are likely to have their signatures modified

**Comment by jleni** [comment]
I will separate unused from unwrap/unexpect.. These are very different things..

**Comment by jleni** [comment]
updated
