### ISSUE TITLE
transactionSign: Add support for Lotus schema

### ISSUE THREAD

**Issue by Schwartz10** [Zondax/filecoin-rs#148]
Currently, `transactionSign` returns a signature that does not conform to the [`SignedMessage` Lotus type](https://github.com/filecoin-project/lotus/blob/master/chain/types/signedmessage.go#L44). The result of `transactionSign` looks like:

```
{
message: {
  from: "t137sjdbgunloi7couiy4l5nc7pd6k2jmq32vizpy"
  gaslimit: 1000
  gasprice: "1"
  method: 0
  nonce: 0
  params: ""
  to: "t137sjdbgunloi7couiy4l5nc7pd6k2jmq32vizpy"
  value: "10000000000000"
}, 
signature: {
  data: "NsyFTDHp0DCOMGGrYNux5Iaxbgb6qkuWyYYopHsviGQFzrgcIPNa0BZYdnbvsr6b4fBV4wB5lxqF9xxBYtBEYgE="
  type: "secp256k1"
}
```

This has a couple problems. 

1. the [`Message` type](https://github.com/filecoin-project/lotus/blob/master/chain/types/message.go#L27) has different capitalizations. For instance, `to` should be `To`,`from` should be `From`...etc. I'm not 100% sure if this is causing transactions to fail, but I'm _pretty_ sure it is.
 2. the [`Signature` type](https://github.com/filecoin-project/specs-actors/blob/master/actors/crypto/signature.go#L36), `Type` field is now its own [`SigType`](https://github.com/filecoin-project/specs-actors/blob/master/actors/crypto/signature.go#L12) of bytes.

I believe once these two things are fixed, the output of `transactionSign` should be able to be inputted into `MpoolPush`

**Comment by jleni** [comment]
This is related to this other issue https://github.com/Zondax/filecoin-rs/issues/120
@rllola 

Once we reactivate the testnet3 unit tests any of this issues should be evident. We were talking about reactivating the tests a few hours ago :)

**Comment by jleni** [comment]
Linking to https://github.com/Zondax/filecoin-rs/issues/124 so we can track this as part of the testnet3 upgrade

**Comment by rllola** [comment]
We have the new PR ready in order to add those improvements : https://github.com/Zondax/filecoin-rs/pull/156

It does has a new function `transactionSignLotus` that will return a JSON formatted signed message answer.
example of answer : 
```
'{
        "Message": {
          "From": "t1d2xrzcslx7xlbbylc5c3d5lvandqw4iwl6epxba",
          "GasLimit": 25000,
          "GasPrice": "2500",
          "Method": 0,
          "Nonce": 1,
          "Params": "",
          "To": "t17uoq6tp427uzv7fztkbsnn64iwotfrristwpryy",
          "Value": "100000"
        },
        "Signature": {
          "Data": "BjmEhQYMoqTeuXAn9Rj0VWk2DDhzpDA5JvppCacpnUxViDRjEgg2NY/zOWiC7g3CzxWWG9SVzfs94e4ui9N2jgE=",
          "Type": 1
        }
      }'
```
