### ISSUE TITLE
keyRecover: Add support for Base64 keys

### ISSUE THREAD

**Issue by Schwartz10** [Zondax/filecoin-rs#154]
I remember having a discussion about this previously, but I don't remember what the conclusion was.

I have a private key that a Lotus node has returned to me directly: `DU1DkMquULRDovTdiCSCdF9AWTYSI49fxPfrYi5SZf4=`, when passing this as the argument to `keyRecover` I get the `Cannot parse hextstring`. 

When I use a key that matches the example code, the call works fine. 

Not sure what the best solution is here, but I vaguely remember @jleni saying this library would handle the key discrepancies?

**Comment by jleni** [comment]
Well yes, that is not a hexstring.. that is base64.
At the moment, we support:
- hexstrings
- Buffer / uint64arrays

I think we have Lotus API related issues.. we can add base64, that would not be a problem.
But given the other Lotus vs Forest compatibility issues, I think it would be good to have a draft spec for all the things you need on the plain signer.

**Comment by jleni** [comment]
I will rename the issue so it is easier to track
