### ISSUE TITLE
Cbindgen problem

### ISSUE THREAD

**Issue by lishuailibertine** [Zondax/filecoin-rs#177]
![image](https://user-images.githubusercontent.com/7145192/84231333-82347300-ab20-11ea-9001-e6d5b296a319.png)

issue：Do I need to implement these undefined functions myself？

**Comment by lishuailibertine** [comment]
@c410-f3r Ok, thank you for your answer，I have another question that I would like to ask.
below is a screenshot of the generated filecoin_sign.h header file：

<img width="1348" alt="image" src="https://user-images.githubusercontent.com/7145192/84336358-adbf6800-abc9-11ea-9353-1a76f9f73ee3.png">

Executed command：
> cbindgen --config /Users/kk/Downloads/filecoin-rs-master/signer-ffi/cbindgen.toml  --crate filecoin-signer --output filecoin_signer.h -v

Executed result image：
![image](https://user-images.githubusercontent.com/7145192/84336754-89b05680-abca-11ea-882d-2815dc7937b0.png)



issue：There seems to be a lot of missing definitions in the header file,I want to generate a complete definition, how do I do that?

**Comment by c410-f3r** [comment]
It is probably because the target crate should be `filecoin-signer-ffi` instead of `filecoin-signer`.

```bash
cbindgen --config /Users/kk/Downloads/filecoin-rs-master/signer-ffi/cbindgen.toml --crate filecoin-signer-ffi --output filecoin_signer.h -v
```

**Comment by lishuailibertine** [comment]
@c410-f3r 

below is a screenshot(This header file that I generated yesterday):

![image](https://user-images.githubusercontent.com/7145192/84338342-5a9be400-abce-11ea-81da-a636127febb1.png)

The function in filecoin-signer ffi.h doesn't have the function interface I want, and I think the function interface I want should be the target in filecoin-signer

<img width="769" alt="image" src="https://user-images.githubusercontent.com/7145192/84338413-83bc7480-abce-11ea-8020-8098efc5a458.png">

**Comment by c410-f3r** [comment]
`ExtendedKey` is a opaque structure because we deal with it internally in the Rust side. It is possible and trivial to expose its field but maybe it should be desired to avoid conflicts.

**Comment by lishuailibertine** [comment]
@c410-f3r 
Okay, thank you. Good night💤
