### ISSUE TITLE
Lotus integration - Determine network

### ISSUE THREAD

**Issue by jleni** [Zondax/filecoin-rs#32]
Connect to Lotus compatible services and determine network (mainnet/testnet)

**Comment by jleni** [comment]
@eshon Pushing to M4 as it depends on Lotus supporting this

**Comment by jleni** [comment]
This issue is blocking progress in other areas.
I see this possible workaround that we can abstract away behind our interface until Lotus API has a more specific method

The following method [WalletBalance](https://documenter.getpostman.com/view/4872192/SWLh5mUd?version=latest#88f146fe-232e-4624-a6e7-97e53776146b)  retrieve information for some specific testnet or mainnet wallets. We can temporarily query for addresses existing in the genesis block. I would expect that a query for an address starting with the incorrect 't' or 'm' prefix will be rejected with an adequate error. Could we use this as part of our internal network detection for now? I think it is worth investigating.

The reason I don't suggest using [WalletNew](https://documenter.getpostman.com/view/4872192/SWLh5mUd?version=latest#186483e1-926f-4f22-80ce-418476943c62) is because I don't think that Lotus will purge unused accounts, so calling at service start seems inadequate. Actually I wonder if this is possible DoS attack in Lotus.

**Comment by jleni** [comment]
We need to check if Lotus has plans for an API to do this

**Comment by eshon** [comment]
@jleni @rllola 

Magik6k said they keep a 'network name' in the init actor state and the API exposes an RPC which returns it:

`StateNetworkName(context.Context) (dtypes.NetworkName, error)`

**Comment by jleni** [comment]
Thanks! This seems very useful, we will check
