### ISSUE TITLE
Fail to parse transaction

### ISSUE THREAD

**Issue by rllola** [Zondax/filecoin-rs#74]
Fail to parse this transaction :
```
885501fd1d0f4dfcd7e99afcb99a8326b7dc459d32c62855015d77a86f78f72f2f71edc37ce67cb344417ea1520242000140400040'
```

By accident I have passed an extra caracter "`" and it panicked instead of sending an error.

log 
```
The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value: InvalidLength
Location: src/libcore/result.rs:1165

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

**Comment by c410-f3r** [comment]
`InvalidLength` is a built-in error that occurs when one passes an odd or zero length string reference to `from_hex_string`. If panic is not desirable, then the documentation should be updated to, e.g., print an user friendly message, use some third-party dependency like `thiserror` or use a single error structure across the signing process.

**Comment by rllola** [comment]
Yeah for some reason there is an unwanted `unwrap()` call here :
https://github.com/Zondax/filecoin-rs/blob/master/service/src/service/methods.rs#L155

It is why it is panicking.

**Comment by jleni** [comment]
@rllola is this still open?

**Comment by rllola** [comment]
I believe it has been fixed.
